services: 
  frontend:
    image: cpnv-es-ria2/frontend
    networks:
      - frontend-backend
    environment:
      - VITE_API_GATEWAY_URL=${VITE_API_GATEWAY_URL}
    ports:
      - "80:80"

  backend:
    image: cpnv-es-ria2/gateway
    networks:
      - frontend-backend
    environment:
      - VISION_ENDPOINT=${VISION_ENDPOINT}
      - VISION_KEY=${VISION_KEY}
      - AZURE_DATA_STORAGE_CONNECTION_STRING=${AZURE_DATA_STORAGE_CONNECTION_STRING}
      - BUCKET_URI=${BUCKET_URI}
    ports:
      - "8080:80"
      - "4443:4443"

networks:
  frontend-backend: {}