services: 
  frontend:
    image: ghcr.io/cpnv-es-ria2/frontend:main
    networks:
      - frontend-backend
    command: 
      - echo "server {listen       80;listen  [::]:80;server_name  localhost;location / {root   /usr/share/nginx/html;index  index.html index.htm;}location /Analyze {proxy_pass http://backend;}error_page   500 502 503 504  /50x.html;location = /50x.html {root   /usr/share/nginx/html;}" > /etc/nginx/conf.d/default.conf

  backend:
    image: ghcr.io/cpnv-es-ria2/backend:main
    networks:
      - frontend-backend
    environment:
      - VISION_ENDPOINT=${VISION_ENDPOINT}
      - VISION_KEY=${VISION_KEY}
      - AZURE_DATA_STORAGE_CONNECTION_STRING=${AZURE_DATA_STORAGE_CONNECTION_STRING}
      - BUCKET_URI=${BUCKET_URI}

networks:
  frontend-backend: {}